-- MySQL Script generated by MySQL Workbench
-- Sun Nov 29 15:05:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema DriverRewards
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DriverRewards
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DriverRewards` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `DriverRewards` ;

-- -----------------------------------------------------
-- Table `DriverRewards`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`auth_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  `phone` CHAR(10) NOT NULL,
  `address_` VARCHAR(100) NOT NULL,
  `preferred_name` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 68
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`Admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`Admins` (
  `Username` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Username`),
  CONSTRAINT `AdAccFK`
    FOREIGN KEY (`Username`)
    REFERENCES `DriverRewards`.`auth_user` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`Drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`Drivers` (
  `Username` VARCHAR(150) NOT NULL,
  `Points_Alert` TINYINT(1) NOT NULL,
  `Order_Placed_Alert` TINYINT(1) NOT NULL,
  `Order_Issue_Alert` TINYINT(1) NOT NULL,
  `Temp_Uname` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`Username`),
  CONSTRAINT `DrAccFK`
    FOREIGN KEY (`Username`)
    REFERENCES `DriverRewards`.`auth_user` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`Driver_Alerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`Driver_Alerts` (
  `ID` INT(11) NOT NULL,
  `Username` VARCHAR(150) NOT NULL,
  `Type_` CHAR(2) NOT NULL,
  `Message_` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `AlDrFk` (`Username` ASC) VISIBLE,
  CONSTRAINT `AlDrFk`
    FOREIGN KEY (`Username`)
    REFERENCES `DriverRewards`.`Drivers` (`Username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`Employers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`Employers` (
  `ID` INT(11) NOT NULL,
  `Name_` VARCHAR(150) NOT NULL,
  `PointsPerDollar` DECIMAL(6,2) NOT NULL,
  `Join_Code` INT(11) NOT NULL,
  `API_Keyword` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`Driver_Points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`Driver_Points` (
  `Driver_User` VARCHAR(150) NOT NULL,
  `Employer_ID` INT(11) NOT NULL,
  `Point_Total` INT(11) NOT NULL,
  `Approved` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Driver_User`, `Employer_ID`),
  INDEX `DPEmpFK` (`Employer_ID` ASC) VISIBLE,
  CONSTRAINT `DPDrFK`
    FOREIGN KEY (`Driver_User`)
    REFERENCES `DriverRewards`.`Drivers` (`Username`),
  CONSTRAINT `DPEmpFK`
    FOREIGN KEY (`Employer_ID`)
    REFERENCES `DriverRewards`.`Employers` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`Invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`Invoices` (
  `ID` INT(11) NOT NULL,
  `Month_End_Date` DATE NOT NULL,
  `Total` DECIMAL(8,2) NOT NULL,
  `Employer_ID` INT(11) NOT NULL,
  `Paid` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `InvEmpFK` (`Employer_ID` ASC) VISIBLE,
  CONSTRAINT `InvEmpFK`
    FOREIGN KEY (`Employer_ID`)
    REFERENCES `DriverRewards`.`Employers` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`Sponsors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`Sponsors` (
  `Username` VARCHAR(150) NOT NULL,
  `Employer_ID` INT(11) NOT NULL,
  `Temp_Uname` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`Username`),
  INDEX `SpEmpFK` (`Employer_ID` ASC) VISIBLE,
  CONSTRAINT `SpAccFK`
    FOREIGN KEY (`Username`)
    REFERENCES `DriverRewards`.`auth_user` (`username`),
  CONSTRAINT `SpEmpFK`
    FOREIGN KEY (`Employer_ID`)
    REFERENCES `DriverRewards`.`Employers` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`Point_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`Point_History` (
  `ID` INT(11) NOT NULL,
  `Username` VARCHAR(150) NOT NULL,
  `Employer_ID` INT(11) NOT NULL,
  `Date_` DATETIME NOT NULL,
  `Point_Cost` INT(11) NOT NULL,
  `Type_Of_Change` CHAR(3) NOT NULL,
  `Sponsor_ID` VARCHAR(150) NULL DEFAULT NULL,
  `Admin_ID` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `PntAccFK` (`Username` ASC) VISIBLE,
  INDEX `PntSpFK` (`Sponsor_ID` ASC) VISIBLE,
  INDEX `PntAdmFK` (`Admin_ID` ASC) VISIBLE,
  INDEX `PntEmpFK` (`Employer_ID` ASC) VISIBLE,
  CONSTRAINT `PntAccFK`
    FOREIGN KEY (`Username`)
    REFERENCES `DriverRewards`.`Drivers` (`Username`),
  CONSTRAINT `PntAdmFK`
    FOREIGN KEY (`Admin_ID`)
    REFERENCES `DriverRewards`.`Admins` (`Username`),
  CONSTRAINT `PntEmpFK`
    FOREIGN KEY (`Employer_ID`)
    REFERENCES `DriverRewards`.`Employers` (`ID`),
  CONSTRAINT `PntSpFK`
    FOREIGN KEY (`Sponsor_ID`)
    REFERENCES `DriverRewards`.`Sponsors` (`Username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`Purchase_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`Purchase_History` (
  `ID` INT(11) NOT NULL,
  `Username` VARCHAR(150) NOT NULL,
  `Employer_ID` INT(11) NOT NULL,
  `Date_` DATETIME NOT NULL,
  `Point_Total` INT(11) NOT NULL,
  `Product_Name` VARCHAR(150) NOT NULL,
  `Sponsor_ID` VARCHAR(150) NULL DEFAULT NULL,
  `Admin_ID` VARCHAR(150) NULL DEFAULT NULL,
  `Product_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `PchAccFK` (`Username` ASC) VISIBLE,
  INDEX `PchSpFK` (`Sponsor_ID` ASC) VISIBLE,
  INDEX `PchAdmFK` (`Admin_ID` ASC) VISIBLE,
  INDEX `PchEmpFK` (`Employer_ID` ASC) VISIBLE,
  CONSTRAINT `PchAccFK`
    FOREIGN KEY (`Username`)
    REFERENCES `DriverRewards`.`Drivers` (`Username`),
  CONSTRAINT `PchAdmFK`
    FOREIGN KEY (`Admin_ID`)
    REFERENCES `DriverRewards`.`Admins` (`Username`),
  CONSTRAINT `PchEmpFK`
    FOREIGN KEY (`Employer_ID`)
    REFERENCES `DriverRewards`.`Employers` (`ID`),
  CONSTRAINT `PchSpFK`
    FOREIGN KEY (`Sponsor_ID`)
    REFERENCES `DriverRewards`.`Sponsors` (`Username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`Shopping_Cart_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`Shopping_Cart_Items` (
  `ID` INT(11) NOT NULL,
  `Username` VARCHAR(150) NOT NULL,
  `Employer_ID` INT(11) NOT NULL,
  `Point_Cost` INT(11) NOT NULL,
  `Sponsor_ID` VARCHAR(150) NULL DEFAULT NULL,
  `Admin_ID` VARCHAR(150) NULL DEFAULT NULL,
  `Product_ID` BIGINT(20) NOT NULL,
  `Product_Name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `CrtAccFK` (`Username` ASC) VISIBLE,
  INDEX `CrtSpFK` (`Sponsor_ID` ASC) VISIBLE,
  INDEX `CrtAdmFK` (`Admin_ID` ASC) VISIBLE,
  INDEX `CrtEmpFK` (`Employer_ID` ASC) VISIBLE,
  CONSTRAINT `CrtAccFK`
    FOREIGN KEY (`Username`)
    REFERENCES `DriverRewards`.`Drivers` (`Username`),
  CONSTRAINT `CrtAdmFK`
    FOREIGN KEY (`Admin_ID`)
    REFERENCES `DriverRewards`.`Admins` (`Username`),
  CONSTRAINT `CrtEmpFK`
    FOREIGN KEY (`Employer_ID`)
    REFERENCES `DriverRewards`.`Employers` (`ID`),
  CONSTRAINT `CrtSpFK`
    FOREIGN KEY (`Sponsor_ID`)
    REFERENCES `DriverRewards`.`Sponsors` (`Username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`auth_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`django_content_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`auth_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT(11) NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `DriverRewards`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`auth_group_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `DriverRewards`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `DriverRewards`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`auth_user_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `DriverRewards`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `DriverRewards`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`auth_user_user_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `DriverRewards`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `DriverRewards`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`django_admin_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT(5) UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC) VISIBLE,
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `DriverRewards`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `DriverRewards`.`auth_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`django_migrations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DriverRewards`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriverRewards`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
